controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true
    controllers: ["joint_state_broadcaster", "diff_drive_controller"]

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster  
    
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:   
    use_stamped_vel: false
    left_wheel_names: ["J1", "J2"]
    right_wheel_names: ["J3", "J4"]
    wheels_per_side: 2
    wheel_separation: 0.620
    wheel_radius: 0.135
    open_loop: false
    odom_frame_id: odom
    base_frame_id: base_link_diff
    velocity_rolling_window_size: 10
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    enable_odom_tf: true
    publish_rate: 50.0
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0

